[package]
name = "bonnet"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-graphics = "0.8.1"
linux-embedded-hal = "0.4.0"
ssd1306 = "0.9.0"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
